export const language = {
	en: {
		action: `Action`,
		app: `Lunar`,
		appearance: `Appearance`,
		associatedMessagesInfo: `Associated messages will display here`,
		associatedMessagesLoading: `Getting associated messages`,
		associatedMessagesNotFound: `No associated messages found`,
		bio: `Bio`,
		chooseAppAppearance: `Choose app appearance`,
		close: `Close`,
		connect: `Connect`,
		connectWallet: `Connect your wallet`,
		connectToContinue: `Connect your wallet to continue`,
		console: `Console`,
		copied: `Copied`,
		create: `Create`,
		createProfile: `Create your profile`,
		current: `Current`,
		currentOutput: `Current Output`,
		dateCreated: `Date Created`,
		delete: `Delete`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		done: `Done`,
		download: `Download`,
		edit: `Edit`,
		editProfile: `Edit your profile`,
		errorUpdatingProfile: `Error updating profile`,
		explorer: `Explorer`,
		fetching: `Fetching`,
		filter: `Filter`,
		filterBy: `Filter by`,
		goBack: `Go back`,
		handle: `Handle`,
		home: `Home`,
		id: `ID`,
		language: `Language`,
		loading: `Loading`,
		maxCharsReached: `Max chars reached`,
		messages: `Messages`,
		name: `Name`,
		network: `Network`,
		new: `New`,
		next: `Next`,
		none: `None`,
		output: `Output`,
		overview: `Overview`,
		owner: `Owner`,
		page: `Page`,
		pageNotFound: `Page not found`,
		previous: `Previous`,
		processOrMessageId: `Process or Message ID`,
		processOrMessageTagsInfo: `Process or Message tags will display here`,
		profile: `Profile`,
		profileCreated: `Profile created`,
		profileCreatingInfo: `Creating your profile`,
		profileMenu: `Profile menu`,
		profileUpdated: `Profile updated`,
		profileUpdatingInfo: `Updating your profile`,
		remove: `Remove`,
		removeAvatar: `Remove avatar`,
		removeBanner: `Remove banner`,
		results: `Results`,
		resultingMessagesInfo: `Resulting messages will display here`,
		save: `Save`,
		sidebarClose: `Close sidebar`,
		sidebarOpen: `Open sidebar`,
		search: `Search`,
		searching: `Searching`,
		showingRange: (start: number, end: number, total: number) => `Showing ${start} - ${end} of ${total}`,
		sortNewestToOldest: `Newest to Oldest`,
		sortOldestToNewest: `Oldest to Newest`,
		tags: `Tags`,
		themes: `Themes`,
		time: `Time`,
		to: `To`,
		top: `Top`,
		type: `Type`,
		untitled: `Untitled`,
		updating: `Updating`,
		uploadAvatar: `Upload avatar`,
		uploadBanner: `Upload banner`,
		view: `View`
	},
};
