name: Deploy To Arweave & ARNS

on:
  push:
    branches:
      - main

jobs:
  Arweave-build-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Clean lockfile (if needed)
        run: rm -rf package-lock.json node_modules

      - name: Check required secrets
        run: |
          if [ -z "$DEPLOY_KEY" ]; then
            echo "Error: DEPLOY_KEY secret is required but not set"
            exit 1
          fi
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy to Arweave
        run: npm run deploy:main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
